/*******************************************************************
 Datalines for CHAPTER8PARMFILE dataset 
 Generated by %mp_ds2cards()
 Licensed under GNU, available on github.com/boemska/macrocore
********************************************************************/
data template.Chapter8parmfile ;
attrib 
hashTable                        length= $32 label="Member Name"
Column                           length= $32 label="Column Name"
is_A_Key                         length= 8
;
infile cards dsd delimiter=',';
input 
   hashTable                        :$char.
   Column                           :$char.
   is_A_Key
;
datalines4;
BYDAYOFWEEK,DayOfWeek,1
BYDAYOFWEEK,PAs,0
BYDAYOFWEEK,AtBats,0
BYDAYOFWEEK,Hits,0
BYDAYOFWEEK,BA,0
BYDAYOFWEEK,OBP,0
BYDAYOFWEEK,SLG,0
BYDAYOFWEEK,OPS,0
BYDAYOFWEEK,_Bases,0
BYDAYOFWEEK,_Reached_Base,0
BYMONTH,Month,1
BYMONTH,PAs,0
BYMONTH,AtBats,0
BYMONTH,Hits,0
BYMONTH,BA,0
BYMONTH,OBP,0
BYMONTH,SLG,0
BYMONTH,OPS,0
BYMONTH,_Bases,0
BYMONTH,_Reached_Base,0
BYPLAYER,Last_Name,1
BYPLAYER,First_Name,1
BYPLAYER,Batter_ID,1
BYPLAYER,PAs,0
BYPLAYER,AtBats,0
BYPLAYER,Hits,0
BYPLAYER,BA,0
BYPLAYER,OBP,0
BYPLAYER,SLG,0
BYPLAYER,OPS,0
BYPLAYER,_Bases,0
BYPLAYER,_Reached_Base,0
BYPLAYERMONTH,Last_Name,1
BYPLAYERMONTH,First_Name,1
BYPLAYERMONTH,Batter_ID,1
BYPLAYERMONTH,Month,1
BYPLAYERMONTH,PAs,0
BYPLAYERMONTH,AtBats,0
BYPLAYERMONTH,Hits,0
BYPLAYERMONTH,BA,0
BYPLAYERMONTH,OBP,0
BYPLAYERMONTH,SLG,0
BYPLAYERMONTH,OPS,0
BYPLAYERMONTH,_Bases,0
BYPLAYERMONTH,_Reached_Base,0
BYTEAM,Team_Name,1
BYTEAM,Team_SK,1
BYTEAM,PAs,0
BYTEAM,AtBats,0
BYTEAM,Hits,0
BYTEAM,BA,0
BYTEAM,OBP,0
BYTEAM,SLG,0
BYTEAM,OPS,0
BYTEAM,_Bases,0
BYTEAM,_Reached_Base,0
;;;;
run;
