/*******************************************************************
 Datalines for CHAPTER9LOOKUPTABLES dataset 
 Generated by %mp_ds2cards()
 Licensed under GNU, available on github.com/boemska/macrocore
********************************************************************/
data template.Chapter9lookuptables ;
attrib 
hashTable                        length= $32 label="Member Name"
Column                           length= $32 label="Column Name"
Is_A_Key                         length= 8
datasetTag                       length= $200
;
infile cards dsd delimiter=',';
input 
   hashTable                        :$char.
   Column                           :$char.
   Is_A_Key
   datasetTag                       :$char.
;
datalines4;
GAMES,Game_SK,1,DW.GAMES
GAMES,Date,0,DW.GAMES
GAMES,Time,0,DW.GAMES
GAMES,Year,0,DW.GAMES
GAMES,Month,0,DW.GAMES
GAMES,DayOfWeek,0,DW.GAMES
GAMES,League,0,DW.GAMES
GAMES,Home_SK,0,DW.GAMES
GAMES,Away_SK,0,DW.GAMES
PLAYERS,Player_ID,1,DW.PLAYERS
PLAYERS,Team_SK,0,DW.PLAYERS
PLAYERS,First_Name,0,DW.PLAYERS
PLAYERS,Last_Name,0,DW.PLAYERS
PLAYERS,Bats,0,DW.PLAYERS
PLAYERS,Throws,0,DW.PLAYERS
PLAYERS,Start_Date,0,DW.PLAYERS
PLAYERS,End_Date,0,DW.PLAYERS
TEAMS,Team_SK,1,DW.TEAMS
TEAMS,Team_Name,0,DW.TEAMS
TEAMS,League_SK,0,DW.TEAMS
;;;;
run;
